spring:
  datasource:
    url: jdbc:mysql://localhost:3306/timeclockdatabase
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update # `create`, `update`, `validate`, or `none`
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
