spring:
  datasource:
    url: jdbc:mysql://localhost:3306/your_database
    username: admin
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update # `create`, `update`, `validate`, or `none`
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
